# Generated by Django 5.1.6 on 2025-02-13 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0004_alter_comment_post_alter_commentlike_comment_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='saveitem',
            unique_together=set(),
        ),
    ]
