# Generated by Django 5.1.6 on 2025-02-13 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0005_alter_saveitem_unique_together'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Save',
            new_name='Saves',
        ),
    ]
