# Generated by Django 5.1.6 on 2025-02-13 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0006_rename_save_saves'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saveitem',
            old_name='save',
            new_name='saves',
        ),
    ]
