# Generated by Django 5.1.6 on 2025-02-13 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0008_alter_saveitem_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saveitem',
            old_name='saves',
            new_name='save_item',
        ),
        migrations.AlterUniqueTogether(
            name='saveitem',
            unique_together={('post', 'save_item')},
        ),
    ]
