# Generated by Django 5.1.6 on 2025-02-13 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0009_rename_saves_saveitem_save_item_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saveitem',
            old_name='save_item',
            new_name='save_cart',
        ),
        migrations.AlterUniqueTogether(
            name='saveitem',
            unique_together={('post', 'save_cart')},
        ),
    ]
