# Generated by Django 5.1.6 on 2025-02-13 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0010_rename_save_item_saveitem_save_cart_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='saveitem',
            unique_together=set(),
        ),
    ]
