# Generated by Django 5.1.6 on 2025-02-13 02:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0011_alter_saveitem_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saveitem',
            name='save_cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_items', to='instagram.saves'),
        ),
        migrations.AlterField(
            model_name='saves',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
