# Generated by Django 5.1.6 on 2025-02-13 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0012_alter_saveitem_save_cart_alter_saves_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='saveitem',
            unique_together={('post', 'save_cart')},
        ),
    ]
